<!--  Copyright (c) Files Community. SPDX-License-Identifier: MPL-2.0  -->
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>$(WindowsTargetFramework)</TargetFramework>
		<TargetPlatformMinVersion>$(MinimalWindowsVersion)</TargetPlatformMinVersion>
		<IsTestProject>true</IsTestProject>
		<IsPackable>false</IsPackable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWindowsForms>true</UseWindowsForms>
		<UseWPF>true</UseWPF>
		<Configurations>Debug;Release</Configurations>
		<Platforms>x86;x64;arm64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<EnableMSTestRunner>true</EnableMSTestRunner>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MSTest.TestAdapter" />
		<PackageReference Include="MSTest.TestFramework" />
		<PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
	</ItemGroup>

</Project>
