<!--  Copyright (c) Files Community. SPDX-License-Identifier: MPL-2.0  -->
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(WindowsTargetFramework)</TargetFramework>
		<TargetPlatformMinVersion>$(MinimalWindowsVersion)</TargetPlatformMinVersion>
		<OutputType>Exe</OutputType>
		<IsPackable>false</IsPackable>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<IsTestProject>true</IsTestProject>
		<Nullable>enable</Nullable>
		<Configurations>Debug;Release</Configurations>
		<Platforms>x86;x64;arm64</Platforms>
		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
		<WindowsAppSDKSelfContained>false</WindowsAppSDKSelfContained>
		<WindowsAppSdkBootstrapInitialize>false</WindowsAppSdkBootstrapInitialize>
		<WindowsAppSdkDeploymentManagerInitialize>false</WindowsAppSdkDeploymentManagerInitialize>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MSTest.TestAdapter" />
		<PackageReference Include="MSTest.TestFramework" />
		<PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Files\Files.csproj" AdditionalProperties="WindowsAppSDKSelfContained=false;WindowsAppSdkBootstrapInitialize=false;WindowsAppSdkDeploymentManagerInitialize=false" />
	</ItemGroup>

</Project>
