# Copyright (c) Files Community
# Licensed under the MIT License.

name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'assets/**'
      - 'builds/**'
      - 'docs/**'
      - '*.md'
  pull_request:
    paths-ignore:
      - 'assets/**'
      - 'builds/**'
      - 'docs/**'
      - '*.md'

run-name: ${{ github.event_name == 'pull_request' && 'PR validation' || 'CI validation' }}

env:
  WORKING_DIR:       ${{ github.workspace }} # Default: 'D:\a\Files\Files'
  SOLUTION_PATH:    '${{ github.workspace }}\Files.slnx'
  APP_PROJECT_PATH: '${{ github.workspace }}\src\Files\Files.csproj'

jobs:

  build:
    runs-on: windows-2025-vs2026
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]
        platform: [x64, arm64]
    env:
      CONFIGURATION: ${{ matrix.configuration }}
      ARCHITECTURE: ${{ matrix.platform }}

    steps:

    - name: Checkout the repository
      uses: actions/checkout@v6
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v3
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json

    - name: Restore
      shell: pwsh
      run: |
        msbuild $env:SOLUTION_PATH `
          -t:Restore -p:Platform=$env:ARCHITECTURE -p:Configuration=$env:CONFIGURATION -p:PublishReadyToRun=true -v:quiet

    # - name: Build Files.Core tests
    #   run: >
    #     dotnet build tests/Files.UnitTests/Files.UnitTests.csproj --configuration ${{ matrix.configuration }} --no-restore -p:Platform=${{ matrix.platform }}

    # - name: Run Files.Core tests
    #   run: >
    #     dotnet test tests/Files.UnitTests/Files.UnitTests.csproj --configuration ${{ matrix.configuration }} --no-build -p:Platform=${{ matrix.platform }}

    # - name: Run benchmark smoke test
    #   run: >
    #     dotnet run --project tests/Files.Benchmarks/Files.Benchmarks.csproj --configuration ${{ matrix.configuration }} -p:Platform=${{ matrix.platform }} -- --smoke

    - name: Build
      shell: pwsh
      run: |
        msbuild $env:APP_PROJECT_PATH `
          -t:Build -p:Configuration=$env:CONFIGURATION -p:Platform=$env:ARCHITECTURE -p:AppxBundle=Never -p:GenerateAppxPackageOnBuild=false -v:quiet
